export const LOCAL_STORAGE_KEY = 'LOCAL_STORAGE_KEY';
export const STORE_LIMIT = 5 * 1024 * 1024;

//actions
export const PHOTO_IMG_LOAD = 'PHOTO_IMG_LOAD';
export const ERROR = 'ERROR';
export const PHOTO_START_OVER = 'PHOTO_START_OVER';
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const DIALOG_CHANGE_TITLE = 'DIALOG_CHANGE_TITLE';
export const DIALOG_CHANGE_IMAGE = 'DIALOG_CHANGE_IMAGE';
export const DIALOG_IMAGE_ERROR = 'DIALOG_IMAGE_ERROR';
export const STICKER_CHANGE_SIZES = 'STICKER_CHANGE_SIZES';
export const PHOTO_STICKER_DELETE = 'PHOTO_STICKER_DELETE';
export const STICKER_DELETE = 'STICKER_DELETE';
export const SUBMIT_STICKER = 'SUBMIT_STICKER';
export const ADD_STICKER = 'ADD_STICKER';
export const ERROR_LIMIT_EXCEED = 'ERROR_LIMIT_EXCEED';


